apiVersion: apps/v1
kind: Deployment
metadata:
  name: mindie-motor-kv-pool
  labels:
    app: mindie-motor-kv-pool
  namespace: mindie-tmx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mindie-motor-kv-pool
  template:
    metadata:
      labels:
        app: mindie-motor-kv-pool
        deploy-name: mindie-motor-kv-pool
    spec:
      terminationGracePeriodSeconds: 0
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 1001
      containers:
      - image: mindie-motor-vllm:dev-26.0.0.B130-800I-A3-py311-Ubuntu24.04-lts-aarch64-mooncake
        imagePullPolicy: IfNotPresent
        name: mindie-motor-kv-pool
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: Unconfined
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: CONFIGMAP_PATH
          value: /mnt/configmap
        - name: ROLE
          value: kv_pool
        - name: KVP_MASTER_SERVICE
          value: kvp-master.mindie-tmx.svc.cluster.local
        - name: KV_POOL_PORT
          value: '50088'
        - name: KV_POOL_EVICTION_HIGH_WATERMARK_RATIO
          value: '0.9'
        - name: KV_POOL_EVICTION_RATIO
          value: '0.1'
        command:
        - /bin/bash
        - -c
        - " source /mnt/configmap/boot.sh; \n "
        resources:
          requests:
            memory: 2Gi
            cpu: '4'
          limits:
            memory: 4Gi
            cpu: '8'
        volumeMounts:
        - name: motor-config
          mountPath: /mnt/configmap
        - name: coredump
          mountPath: /var/coredump
        - name: ascend-driver
          mountPath: /usr/local/Ascend/driver
      volumes:
      - name: motor-config
        configMap:
          name: motor-config
          defaultMode: 360
      - name: coredump
        hostPath:
          path: /var/coredump
          type: DirectoryOrCreate
      - name: ascend-driver
        hostPath:
          path: /usr/local/Ascend/driver
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mindie-motor-kv-pool
  name: kvp-master
  namespace: mindie-tmx
spec:
  ports:
  - name: business
    port: 50088
    protocol: TCP
    targetPort: 50088
  - name: metrics
    port: 9003
    protocol: TCP
    targetPort: 9003
  selector:
    app: mindie-motor-kv-pool
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
